# BitCrafty Extractor Default Configuration Template
# This is a template file - the application will create config.yaml from this template
# WARNING: Do not commit API keys to version control! Use config.yaml for your keys.

# AI Provider Configuration
ai:
  openai:
    api_key: ""  # Add your OpenAI API key in config.yaml
    model: "gpt-4o"
    enabled: true
    max_tokens: 1000
    temperature: 0.1
    timeout: 30.0
  
  anthropic:
    api_key: ""  # Add your Anthropic API key in config.yaml
    model: "claude-3-5-sonnet-20241022"
    enabled: true
    max_tokens: 1000
    temperature: 0.1
    timeout: 30.0

# Global Hotkey Configuration
hotkeys:
  queue_screenshot: "ctrl+shift+e"
  analyze_queue: "ctrl+shift+x"
  quit_application: "ctrl+shift+q"
  enable_global: true
  debounce_ms: 500

# Screenshot Capture Configuration
capture:
  window_name: "Bitcraft"
  target_process: "bitcraft.exe"
  game_window_patterns:
    - "BitCraft"
    - "bitcraft"
    - "BITCRAFT"
    - "Bitcraft"
  max_image_size: 1024
  image_format: "PNG"
  image_quality: 85
  capture_timeout: 5.0
  queue_max_size: 20
  min_window_width: 400
  min_window_height: 300

# AI Extraction Configuration  
extraction:
  primary_provider: "openai"
  fallback_provider: "anthropic"
  use_fallback: true
  include_examples: true
  min_confidence: 0.7
  max_retries: 3
  rate_limit_delay: 1.0

# Application Settings
log_level: "INFO"
auto_save_results: true
results_directory: "exports"
